version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    networks:
      - mispay
    ports:
      - "5432:5432"
    volumes:
      - ~/data/postgres:/data/postgres
    env_file:
      - docker.env

    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'nestjs'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - mispay
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQGABCDEFGHIJK'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  email-notification-service:
    image: email-notification-service:latest
    networks:
      - mispay
    environment:
      SENDER_EMAIL: 'msajawalsial@gmail.com'
      RABBITMQ_USER: 'admin'
      RABBITMQ_PASSWORD: 'admin'
      RABBITMQ_HOST: rabbitmq:5672
      RABBITMQ_QUEUE_NAME: 'emails'
    depends_on:
      - rabbitmq
  
  user-and-event-service:
    image: user-and-event-service:latest
    build: .
    networks:
      - mispay
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'nestjs'
      PORT: 3000
      RABBITMQ_USER: 'admin'
      RABBITMQ_PASSWORD: 'admin'
      RABBITMQ_HOST: rabbitmq:5672
      RABBITMQ_QUEUE_NAME: 'emails'
      JWT_SECRET: '1234567890'
      JWT_EXPIRATION_TIME_SECONDS: 3600
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"

networks:
  mispay:
    driver: bridge